### PR TITLE
Define the publication date as the approval date

### LINKED ISSUE #21: Identify versions of documents using the year-month approval date instead of the publication date
AG 02, 10.1 currently states:

_Versions of documents shall be identified by their year of publication and, optionally, their month of publication [...]_

However:

* the publication date is not directly related to the last time the document was modified/approved, and thus of limited semantic use to the reader and possibly out-of-sync with any internal date-based identifiers, e.g. URIs

* the publication date is ambiguous when the document is published through multiple channels

* the publication date does not provide any information not already provided by the approval date

Furthermore, the fact that the publication month is optional prevents automation and introduces inconsistencies when referencing documents. Instead versions of documents that are published should consistently be identified by the year and month of the approval date. This is similar to the approach used by the ITU:

image

### PR DESCRIPTION
**Pull request by palemieux**
Closes #21

### CODE REVIEW

**Comment by FredWalls** [comment]
Can we provide some kind of notification for those who access the standards library if we decide to make this change? I'm sure it's possible for people to figure out what happened, but I think it would be beneficial to explain that documents before X date are indexed by publication date, documents after Y date are indexed by approval date, and documents between X and Y dates might be either.

**Comment by palemieux** [comment]
@FredWalls To clarify: today all documents in the [SMPTE document library](https://pub.smpte.org/doc/) are indexed using the approval date.

The change being proposed going forward is to change the date in the document designator, e.g. the `2023` in `ST 2067-21:2023`, from the _publication date_ to the _approval month and year_, e.g. `ST 2067-21:2022-11`.

The date in the document designator will not change for existing document.

See sample at https://github.com/SMPTE/html-pub/pull/190

**Comment by FredWalls** [comment]
@palemieux I'm kind of confused by your statement... when I click on the documents in the new library, the links come up as "published" followed by a date. I would consider this to be indexed by the publication date. But regardless, I think my point stands that whether we say that the change was to the document designator or something else, there needs to be a mention that a change was made to how it was derived.

**Comment by palemieux** [comment]
> I'm kind of confused by your statement... when I click on the documents in the new library, the links come up as "published" followed by a date.

Do you mean, for instance, [Publication (1990-03-28)](https://pub.smpte.org/doc/eg1/19900328-pub/) at https://pub.smpte.org/doc/eg1/ ? If so, _Publication_ refers to the state of the document.

>  But regardless, I think my point stands that whether we say that the change was to the document designator or something else, there needs to be a mention that a change was made to how it was derived.

No disagreement.

**Review by SteveLLamb — APPROVED** [review]

**Pull request merged**
